// In-memory cache of everything this app can buy/sell, refreshed hourly.
// Families, all plain path+count operations server-side (no oid/
// inventory.php resolution needed - see README.md's "Confirmed HTTP
// mechanics" for the source-verified writeup of why):
//
// - Mods + Arcanes (category "Upgrades"): both route through
//   SpaceNinjaServer's identical addMods()/RawUpgrades mechanism. Tagged
//   "mod" or "arcane_enhancement" on warframe.market (NOT "arcane"). Rank
//   (fusion level) is set via a Fingerprint on the grant - see
//   Market Sync.pluto's doBuy() - which is why rank>0 buys land in the
//   unique-instance Upgrades collection and can't be sold back generically.
// - Relics (category "MiscItems"): warframe.market's gameRef for a relic
//   is the BASE path with no refinement suffix - confirmed against the
//   local Public Export dump that appending a suffix produces a real
//   grantable path per refinement, e.g. ".../T1VoidProjectionG" +
//   "Bronze" = ".../T1VoidProjectionGBronze" ("Lith A1", Intact, verified
//   2026-09-17). UNLIKE mod rank, refinement does NOT create a unique
//   instance - each refinement is just a different plain stackable
//   MiscItems ItemType, so buy AND sell both work at any refinement via
//   the same path+count mechanism already proven. `routes.ts` resolves
//   the base gameRef + chosen refinement into the final grantable path at
//   order-creation time, so Market Sync.pluto never needs to know
//   refinement exists at all - it just sees a fully-resolved gameRef,
//   identical to every other order.
// - Prime Warframe parts (ALL 4 members - the main Blueprint AND the 3
//   component Blueprints - are category "Recipes") and sets: see
//   prime-warframe-sets.json (generated by tools/generate-prime-sets.js
//   from the local Public Export dumps, NOT from warframe.market - its
//   bulk /v2/items list omits the setRoot/setParts fields needed to
//   group parts into sets). Confirmed from source that the FINISHED
//   components (e.g. "...SystemsComponent", productCategory MiscItems)
//   are NOT what's actually tradeable - what trades is a separate
//   "...SystemsBlueprint" recipe that BUILDS the finished component from
//   real crafting resources; the generator resolves this two-stage chain
//   so every part gameRef here matches warframe.market's own gameRef
//   exactly. A set's OWN warframe.market gameRef (e.g.
//   "/Lotus/Powersuits/Volt/VoltPrime") is the FINISHED Warframe's own
//   type path - NEVER grant that directly, it would route through
//   addPowerSuit() (unique-instance, avoided
//   deliberately). "Buying a set" instead grants every member part
//   individually via the `parts` array - see routes.ts/Market Sync.pluto.
//
// `category` and `defaultSubtype` ride along on each entry so the price
// lookup (which needs the right warframe.market order subtype) and the
// sell call (which needs the right SpaceNinjaServer Items.<category> key)
// don't have to re-derive them from the item's tags/path again later.
// `type` is the UI-facing grouping (Mods and Arcanes share `category`
// "Upgrades" server-side, but a user filtering the shop wants them split).

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { fetchAllItems, type WfmItemEntry } from "./warframeMarketApi.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export type ItemCategory = "Upgrades" | "MiscItems" | "Recipes";
export type ItemType = "mod" | "arcane" | "relic" | "prime_part" | "prime_set";
export type PrimeSlot = "blueprint" | "helmet" | "chassis" | "systems";

// warframe.market's subtype names -> the real client path suffix for that
// relic refinement. Source: ExportRelics.json (local Public Export dump),
// cross-referenced against warframe.market's own subtype vocabulary.
export const RELIC_REFINEMENT_SUFFIXES: Record<string, string> = {
    intact: "Bronze",
    exceptional: "Silver",
    flawless: "Gold",
    radiant: "Platinum"
};
const DEFAULT_RELIC_REFINEMENTS = Object.keys(RELIC_REFINEMENT_SUFFIXES);

export interface MarketItem {
    slug: string;
    gameRef: string; // relics: BASE path, no suffix. prime_set: the SET's own path - identity/display only, NEVER granted directly. everything else: the real full grantable path.
    name: string;
    icon: string | null;
    category: ItemCategory;
    type: ItemType;
    defaultSubtype: string; // default warframe.market order "subtype" for this item (rank-0 mods: "regular"; relics: "intact")
    maxRank: number | null; // mods/arcanes only, null otherwise
    refinements: string[] | null; // relics only (subset of RELIC_REFINEMENT_SUFFIXES' keys), null otherwise
    parts: { gameRef: string; category: ItemCategory }[] | null; // prime_set only - the member items to grant when buying the whole set
    slot: PrimeSlot | null; // prime_part only - which of the 4 fixed Warframe slots this is, for the UI badge
}

// Every Prime Warframe set's 4 part gameRefs follow one of exactly these 4
// suffixes with zero exceptions - verified across all 50 sets in
// prime-warframe-sets.json (2026-09-17), not assumed from a single example.
// "Blueprint" with no further suffix is the main/full-Warframe blueprint;
// the other 3 are the physical component blueprints.
function primeSlotFromGameRef(gameRef: string): PrimeSlot | null {
    if (/HelmetBlueprint$/.test(gameRef)) return "helmet";
    if (/ChassisBlueprint$/.test(gameRef)) return "chassis";
    if (/SystemsBlueprint$/.test(gameRef)) return "systems";
    if (/Blueprint$/.test(gameRef)) return "blueprint";
    return null;
}

interface PrimeSetDef {
    setGameRef: string;
    parts: { gameRef: string; category: ItemCategory }[];
}

const PRIME_WARFRAME_SETS: PrimeSetDef[] = JSON.parse(
    readFileSync(path.join(__dirname, "../prime-warframe-sets.json"), "utf8")
);

const REFRESH_MS = 60 * 60 * 1000; // 1 hour

let cache: MarketItem[] = [];
let cachedAt = 0;
let refreshing: Promise<MarketItem[]> | null = null;

function iconUrl(icon: string | undefined): string | null {
    return icon ? `https://warframe.market/static/assets/${icon}` : null;
}

function classify(item: WfmItemEntry): MarketItem | null {
    const en = item.i18n.en;
    if (!en || !item.gameRef) return null;

    // Riven placeholders are tagged "riven_mod"/"veiled_riven", NOT the
    // exact "riven" tag this used to check for - that mismatch let 7
    // "Veiled Riven Mod" items slip into the shop (confirmed 2026-09-17
    // by downloading the full catalog and checking real tag names, not
    // guessed). Rivens are excluded entirely: buying/selling a veiled
    // riven from this shop would decrement the SAME stackable ItemType a
    // player's real earned-in-game veiled rivens live in - indistinguishable,
    // so a Sell click here could silently remove a real one.
    const isRiven = item.tags.some(t => t.includes("riven"));

    if (item.tags.includes("arcane_enhancement") && !isRiven) {
        return {
            slug: item.slug,
            gameRef: item.gameRef,
            name: en.name,
            icon: iconUrl(en.icon),
            category: "Upgrades",
            type: "arcane",
            defaultSubtype: "regular",
            maxRank: item.maxRank ?? null,
            refinements: null,
            parts: null,
            slot: null
        };
    }

    if (item.tags.includes("mod") && !isRiven) {
        return {
            slug: item.slug,
            gameRef: item.gameRef,
            name: en.name,
            icon: iconUrl(en.icon),
            category: "Upgrades",
            type: "mod",
            defaultSubtype: "regular",
            maxRank: item.maxRank ?? null,
            refinements: null,
            parts: null,
            slot: null
        };
    }

    if (item.tags.includes("relic")) {
        const refinements = (item.subtypes && item.subtypes.length > 0 ? item.subtypes : DEFAULT_RELIC_REFINEMENTS).filter(
            s => s in RELIC_REFINEMENT_SUFFIXES
        );
        return {
            slug: item.slug,
            gameRef: item.gameRef,
            name: en.name,
            icon: iconUrl(en.icon),
            category: "MiscItems",
            type: "relic",
            defaultSubtype: refinements.includes("intact") ? "intact" : (refinements[0] ?? "intact"),
            maxRank: null,
            refinements,
            parts: null,
            slot: null
        };
    }

    return null;
}

// Built from the locally-generated PRIME_WARFRAME_SETS, cross-referenced
// against the live warframe.market bulk item list purely for display
// data (name/icon/slug/price lookups) - the grouping itself never comes
// from warframe.market (see the module-level comment for why). A set is
// only emitted if BOTH its own listing AND every one of its member parts
// currently resolve against the bulk list - skips gracefully otherwise
// rather than emitting a partial/broken set.
function buildPrimeItems(all: WfmItemEntry[]): MarketItem[] {
    const byGameRef = new Map<string, WfmItemEntry>();
    for (const item of all) {
        if (item.gameRef) byGameRef.set(item.gameRef, item);
    }

    const result: MarketItem[] = [];

    for (const setDef of PRIME_WARFRAME_SETS) {
        const setWfm = byGameRef.get(setDef.setGameRef);
        if (!setWfm?.i18n.en) continue;

        const resolvedParts = setDef.parts.map(def => ({ def, wfm: byGameRef.get(def.gameRef) }));
        if (resolvedParts.some(p => !p.wfm?.i18n.en)) continue;

        for (const { def, wfm } of resolvedParts) {
            const en = wfm!.i18n.en!;
            result.push({
                slug: wfm!.slug,
                gameRef: def.gameRef,
                name: en.name,
                icon: iconUrl(en.icon),
                category: def.category,
                type: "prime_part",
                defaultSubtype: "regular",
                maxRank: null,
                refinements: null,
                parts: null,
                slot: primeSlotFromGameRef(def.gameRef)
            });
        }

        const setEn = setWfm.i18n.en;
        result.push({
            slug: setWfm.slug,
            gameRef: setDef.setGameRef,
            name: setEn.name,
            icon: iconUrl(setEn.icon),
            category: "MiscItems", // unused for granting - the parts[] array below drives the grant loop, never this field
            type: "prime_set",
            defaultSubtype: "regular",
            maxRank: null,
            refinements: null,
            parts: resolvedParts.map(p => p.def),
            slot: null
        });
    }

    return result;
}

async function refresh(): Promise<MarketItem[]> {
    const all = await fetchAllItems();
    const classified = all.map(classify).filter((m): m is MarketItem => m !== null);
    const primeItems = buildPrimeItems(all);
    cache = [...classified, ...primeItems];
    cachedAt = Date.now();
    return cache;
}

export async function getItems(): Promise<MarketItem[]> {
    if (Date.now() - cachedAt < REFRESH_MS && cache.length > 0) {
        return cache;
    }
    if (!refreshing) {
        refreshing = refresh().finally(() => {
            refreshing = null;
        });
    }
    return refreshing;
}

export async function findItemByGameRef(gameRef: string): Promise<MarketItem | undefined> {
    const items = await getItems();
    return items.find(m => m.gameRef === gameRef);
}

export async function findItemBySlug(slug: string): Promise<MarketItem | undefined> {
    const items = await getItems();
    return items.find(m => m.slug === slug);
}

// The real grantable/sellable ItemType path for an item at a given
// refinement - same resolution routes.ts already does when creating a
// sell order, factored out so the owned-count lookup (GET /api/owned)
// stays in sync with it rather than re-deriving the suffix logic
// separately. Only relics vary by refinement; everything else's gameRef
// IS the sellable path already (Sell is always rank-0 for mods/arcanes,
// and Prime parts/sets have no variants at all).
export function resolveSellGameRef(item: MarketItem, refinement?: string): string {
    if (item.type !== "relic") return item.gameRef;
    const chosen = typeof refinement === "string" && item.refinements?.includes(refinement) ? refinement : item.defaultSubtype;
    const suffix = RELIC_REFINEMENT_SUFFIXES[chosen];
    return suffix ? item.gameRef + suffix : item.gameRef;
}
