// In-memory cache of everything this app can buy/sell, refreshed hourly.
// Families, all plain path+count operations server-side (no oid/
// inventory.php resolution needed - see README.md's "Confirmed HTTP
// mechanics" for the source-verified writeup of why):
//
// - Mods + Arcanes (category "Upgrades"): both route through
//   SpaceNinjaServer's identical addMods()/RawUpgrades mechanism. Tagged
//   "mod" or "arcane_enhancement" on warframe.market (NOT "arcane"). Rank
//   (fusion level) is set via a Fingerprint on the grant - see
//   Market Sync.pluto's doBuy() - which is why rank>0 buys land in the
//   unique-instance Upgrades collection and can't be sold back generically.
// - Relics (category "MiscItems"): warframe.market's gameRef for a relic
//   is the BASE path with no refinement suffix - confirmed against the
//   local Public Export dump that appending a suffix produces a real
//   grantable path per refinement, e.g. ".../T1VoidProjectionG" +
//   "Bronze" = ".../T1VoidProjectionGBronze" ("Lith A1", Intact, verified
//   2026-09-17). UNLIKE mod rank, refinement does NOT create a unique
//   instance - each refinement is just a different plain stackable
//   MiscItems ItemType, so buy AND sell both work at any refinement via
//   the same path+count mechanism already proven. `routes.ts` resolves
//   the base gameRef + chosen refinement into the final grantable path at
//   order-creation time, so Market Sync.pluto never needs to know
//   refinement exists at all - it just sees a fully-resolved gameRef,
//   identical to every other order.
// - Prime Warframe parts (ALL 4 members - the main Blueprint AND the 3
//   component Blueprints - are category "Recipes") and sets: see
//   prime-warframe-sets.json (generated by tools/generate-prime-sets.js
//   from the local Public Export dumps, NOT from warframe.market - its
//   bulk /v2/items list omits the setRoot/setParts fields needed to
//   group parts into sets). Confirmed from source that the FINISHED
//   components (e.g. "...SystemsComponent", productCategory MiscItems)
//   are NOT what's actually tradeable - what trades is a separate
//   "...SystemsBlueprint" recipe that BUILDS the finished component from
//   real crafting resources; the generator resolves this two-stage chain
//   so every part gameRef here matches warframe.market's own gameRef
//   exactly. A set's OWN warframe.market gameRef (e.g.
//   "/Lotus/Powersuits/Volt/VoltPrime") is the FINISHED Warframe's own
//   type path - NEVER grant that directly, it would route through
//   addPowerSuit() (unique-instance, avoided
//   deliberately). "Buying a set" instead grants every member part
//   individually via the `parts` array - see routes.ts/Market Sync.pluto.
// - Prime WEAPON parts and sets (also category "Recipes"): see
//   prime-weapon-sets.json (generated by tools/generate-prime-weapon-sets.js).
//   UNLIKE Warframes, a weapon's physical components (Barrel/Receiver/
//   Blade/etc.) ARE directly tradeable Recipes already - no two-stage
//   resolution needed - but part COUNT varies by weapon type (2-4 real
//   parts, confirmed from source across all 87 Prime weapons, not
//   assumed to generalize from the Warframe 4-slot model) and a handful
//   of Akimbo weapons need duplicate copies of the same part, or even a
//   whole other Prime's own part set nested inside (see the generator's
//   header comment for the full, source-confirmed breakdown). `parts` for
//   these sets can therefore contain the same gameRef more than once -
//   buildPrimeCategoryItems() below dedupes that for the flat per-part
//   catalog rows while keeping every duplicate for the actual grant list.
//
// `category` and `defaultSubtype` ride along on each entry so the price
// lookup (which needs the right warframe.market order subtype) and the
// sell call (which needs the right SpaceNinjaServer Items.<category> key)
// don't have to re-derive them from the item's tags/path again later.
// `type` is the UI-facing grouping (Mods and Arcanes share `category`
// "Upgrades" server-side, but a user filtering the shop wants them split).

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { fetchAllItems, type WfmItemEntry } from "./warframeMarketApi.js";
import { getIconPathForGameRef, getLocalIconPath } from "./localIcons.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export type ItemCategory = "Upgrades" | "MiscItems" | "Recipes";
export type ItemType = "mod" | "arcane" | "relic" | "prime_part" | "prime_set";
// "blueprint"/"helmet"/"chassis"/"systems" are the 4 fixed Warframe
// slots; everything else is a weapon part slot (variable count/vocabulary
// per weapon type - see weaponPrimeSlotFromGameRef()).
export type PrimeSlot =
    | "blueprint"
    | "helmet"
    | "chassis"
    | "systems"
    | "barrel"
    | "receiver"
    | "stock"
    | "blade"
    | "handle"
    | "link"
    | "gauntlet"
    | "guard"
    | "head"
    | "disc"
    | "grip"
    | "boot"
    | "chain"
    | "ornament"
    | "string"
    | "upperLimb"
    | "lowerLimb";
export type Rarity = "common" | "uncommon" | "rare" | "legendary";
export type RelicEra = "lith" | "meso" | "neo" | "axi" | "requiem";

// warframe.market's own rarity tags - present on every mod/arcane except
// a handful of mission-scanner/locator mods with no rarity at all
// (confirmed by downloading the full catalog: 1381 of 1391 non-riven mods
// carry exactly one of these). NOTE: "Primed" mods (e.g. Primed
// Continuity) use the SAME "legendary" tag Arcanes use for their top
// tier - warframe.market doesn't have a separate "primed" tag - so the
// UI labels this tier "Primed" on the Mods tab and "Legendary" on the
// Arcanes tab, both reading the same underlying value.
const RARITY_TAGS: Rarity[] = ["common", "uncommon", "rare", "legendary"];
function extractRarity(tags: string[]): Rarity | null {
    return RARITY_TAGS.find(r => tags.includes(r)) ?? null;
}

// Relic era tags, also present directly in the bulk item list - no extra
// per-item lookups needed. A "vanguard" tag exists too (Vanguard Vault
// relics) but it's layered ON TOP of one of these 5 (e.g. a Vanguard
// relic is ALSO tagged "axi"), not a parallel 6th era - confirmed by
// checking a real example, not guessed.
const RELIC_ERA_TAGS: RelicEra[] = ["lith", "meso", "neo", "axi", "requiem"];
function extractRelicEra(tags: string[]): RelicEra | null {
    return RELIC_ERA_TAGS.find(e => tags.includes(e)) ?? null;
}

// warframe.market's subtype names -> the real client path suffix for that
// relic refinement. Source: ExportRelics.json (local Public Export dump),
// cross-referenced against warframe.market's own subtype vocabulary.
export const RELIC_REFINEMENT_SUFFIXES: Record<string, string> = {
    intact: "Bronze",
    exceptional: "Silver",
    flawless: "Gold",
    radiant: "Platinum"
};
const DEFAULT_RELIC_REFINEMENTS = Object.keys(RELIC_REFINEMENT_SUFFIXES);

export interface MarketItem {
    slug: string;
    gameRef: string; // relics: BASE path, no suffix. prime_set: the SET's own path - identity/display only, NEVER granted directly. everything else: the real full grantable path.
    name: string;
    icon: string | null;
    category: ItemCategory;
    type: ItemType;
    defaultSubtype: string; // default warframe.market order "subtype" for this item (rank-0 mods: "regular"; relics: "intact")
    maxRank: number | null; // mods/arcanes only, null otherwise
    refinements: string[] | null; // relics only (subset of RELIC_REFINEMENT_SUFFIXES' keys), null otherwise
    parts: { gameRef: string; category: ItemCategory }[] | null; // prime_set only - the member items to grant when buying the whole set
    slot: PrimeSlot | null; // prime_part only - which Warframe or weapon slot this is, for the UI badge
    rarity: Rarity | null; // mods/arcanes only, null otherwise
    relicEra: RelicEra | null; // relics only, null otherwise
}

// Every Prime Warframe set's 4 part gameRefs follow one of exactly these 4
// suffixes with zero exceptions - verified across all 50 sets in
// prime-warframe-sets.json (2026-09-17), not assumed from a single example.
// "Blueprint" with no further suffix is the main/full-Warframe blueprint;
// the other 3 are the physical component blueprints.
function primeSlotFromGameRef(gameRef: string): PrimeSlot | null {
    if (/HelmetBlueprint$/.test(gameRef)) return "helmet";
    if (/ChassisBlueprint$/.test(gameRef)) return "chassis";
    if (/SystemsBlueprint$/.test(gameRef)) return "systems";
    if (/Blueprint$/.test(gameRef)) return "blueprint";
    return null;
}

// Weapon Prime part gameRefs end in one of these slot names with zero
// exceptions - verified across all 211 real WeaponParts entries feeding
// prime-weapon-sets.json (2026-09-20), not assumed. Order doesn't matter -
// none of these suffixes are a substring of another (e.g. "Grip" never
// collides with "UpperLimb"/"LowerLimb", which are checked as whole
// suffixes, not decomposed into "Upper"/"Lower"/"Limb").
const WEAPON_PART_SLOT_SUFFIXES: [string, PrimeSlot][] = [
    ["Barrel", "barrel"],
    ["Receiver", "receiver"],
    ["Stock", "stock"],
    ["Blade", "blade"],
    ["Handle", "handle"],
    ["Link", "link"],
    ["Gauntlet", "gauntlet"],
    ["Guard", "guard"],
    ["Head", "head"],
    ["Disc", "disc"],
    ["UpperLimb", "upperLimb"],
    ["LowerLimb", "lowerLimb"],
    ["Grip", "grip"],
    ["Boot", "boot"],
    ["Chain", "chain"],
    ["Ornament", "ornament"],
    ["String", "string"]
];
function weaponPrimeSlotFromGameRef(gameRef: string): PrimeSlot | null {
    if (/Blueprint$/.test(gameRef)) return "blueprint";
    const match = WEAPON_PART_SLOT_SUFFIXES.find(([suffix]) => gameRef.endsWith(suffix));
    return match ? match[1] : null;
}

interface PrimeSetDef {
    setGameRef: string;
    parts: { gameRef: string; category: ItemCategory }[];
}

const PRIME_WARFRAME_SETS: PrimeSetDef[] = JSON.parse(
    readFileSync(path.join(__dirname, "../prime-warframe-sets.json"), "utf8")
);

const PRIME_WEAPON_SETS: PrimeSetDef[] = JSON.parse(
    readFileSync(path.join(__dirname, "../prime-weapon-sets.json"), "utf8")
);

// Disk-persisted, seed-then-cache model mirroring priceCache.ts's own
// (proven) shape - see that file's header comment for the full rationale.
// There is deliberately NO time-based auto re-fetch here anymore: the
// catalog only ever changes when the user explicitly triggers "Update
// Data" (routes.ts) - getItems() just serves whatever's already loaded,
// with zero network calls, so it can never reject/502 from being offline.
const CATALOG_FILE = path.join(__dirname, "../items-cache.json");
// Committed real snapshot (like price-history.seed.json) so a fresh
// clone/install has a full catalog immediately instead of an empty shop
// until the user's first "Update Data" click. Only loaded when no local
// items-cache.json exists yet.
const SEED_FILE = path.join(__dirname, "../items-cache.seed.json");

let cache: MarketItem[] = [];
let lastRefreshedAt: number | null = null;
let refreshing: Promise<MarketItem[]> | null = null;

interface DiskCache {
    items: MarketItem[];
    lastRefreshedAt: number | null;
}

function loadFromDisk(): void {
    if (existsSync(CATALOG_FILE)) {
        try {
            const parsed = JSON.parse(readFileSync(CATALOG_FILE, "utf8")) as DiskCache;
            cache = parsed.items ?? [];
            lastRefreshedAt = parsed.lastRefreshedAt ?? null;
            return;
        } catch (err) {
            console.error(`Failed to load ${CATALOG_FILE}, starting empty:`, err);
        }
    }

    if (existsSync(SEED_FILE)) {
        try {
            const parsed = JSON.parse(readFileSync(SEED_FILE, "utf8")) as { items?: MarketItem[] };
            cache = parsed.items ?? [];
            console.log("Item catalog: no local cache found - seeded from the bundled snapshot.");
        } catch (err) {
            console.error(`Failed to load bundled seed ${SEED_FILE}:`, err);
        }
    }
}
loadFromDisk();

function saveToDisk(): void {
    try {
        const disk: DiskCache = { items: cache, lastRefreshedAt };
        writeFileSync(CATALOG_FILE, JSON.stringify(disk));
    } catch (err) {
        console.error(`Failed to save ${CATALOG_FILE}:`, err);
    }
}

// Local-only, no network fallback - warframe.market's own icon hotlink
// (the previous source here) is both a live-network dependency and, per
// the user, currently broken outright. Looks up this item's real gameRef
// in ICON_PATHS (built from Public Export, not warframe.market's own
// icon field - the `icon` parameter this used to take is gone) and
// returns a served /icon-cache/... URL only if that file has actually
// been extracted already (see localIcons.ts) - otherwise null, which the
// frontend renders as a placeholder. Extraction itself only ever happens
// via the explicit "Update Data" action (routes.ts), never triggered from
// here.
function iconUrl(gameRef: string): string | null {
    const iconPath = getIconPathForGameRef(gameRef);
    if (!iconPath) return null;
    const rel = getLocalIconPath(iconPath);
    return rel ? `/icon-cache/${rel}` : null;
}

function classify(item: WfmItemEntry): MarketItem | null {
    const en = item.i18n.en;
    if (!en || !item.gameRef) return null;

    // Riven placeholders are tagged "riven_mod"/"veiled_riven", NOT the
    // exact "riven" tag this used to check for - that mismatch let 7
    // "Veiled Riven Mod" items slip into the shop (confirmed 2026-09-17
    // by downloading the full catalog and checking real tag names, not
    // guessed). Rivens are excluded entirely: buying/selling a veiled
    // riven from this shop would decrement the SAME stackable ItemType a
    // player's real earned-in-game veiled rivens live in - indistinguishable,
    // so a Sell click here could silently remove a real one.
    const isRiven = item.tags.some(t => t.includes("riven"));

    // The 4 "Peculiar" mods (Peculiar Growth/Bloom/Audience/End) carry
    // BOTH "mod" AND "arcane_enhancement" tags simultaneously on
    // warframe.market - confirmed 2026-09-18 by downloading the full
    // catalog: they're the ONLY items with both tags at once, everything
    // else has exactly one or the other. "mod" is checked first so this
    // ambiguous case lands as a Mod (matching what they actually are -
    // Warframe-slot mods, not Arcanes) rather than an Arcane, which is
    // what checking arcane_enhancement first used to produce.
    if (item.tags.includes("mod") && !isRiven) {
        return {
            slug: item.slug,
            gameRef: item.gameRef,
            name: en.name,
            icon: iconUrl(item.gameRef),
            category: "Upgrades",
            type: "mod",
            defaultSubtype: "regular",
            maxRank: item.maxRank ?? null,
            refinements: null,
            parts: null,
            slot: null,
            rarity: extractRarity(item.tags),
            relicEra: null
        };
    }

    if (item.tags.includes("arcane_enhancement") && !isRiven) {
        return {
            slug: item.slug,
            gameRef: item.gameRef,
            name: en.name,
            icon: iconUrl(item.gameRef),
            category: "Upgrades",
            type: "arcane",
            defaultSubtype: "regular",
            maxRank: item.maxRank ?? null,
            refinements: null,
            parts: null,
            slot: null,
            rarity: extractRarity(item.tags),
            relicEra: null
        };
    }

    if (item.tags.includes("relic")) {
        const refinements = (item.subtypes && item.subtypes.length > 0 ? item.subtypes : DEFAULT_RELIC_REFINEMENTS).filter(
            s => s in RELIC_REFINEMENT_SUFFIXES
        );
        return {
            slug: item.slug,
            gameRef: item.gameRef,
            name: en.name,
            icon: iconUrl(item.gameRef),
            category: "MiscItems",
            type: "relic",
            defaultSubtype: refinements.includes("intact") ? "intact" : (refinements[0] ?? "intact"),
            maxRank: null,
            refinements,
            parts: null,
            slot: null,
            rarity: null,
            relicEra: extractRelicEra(item.tags)
        };
    }

    return null;
}

// Built from the locally-generated set defs (PRIME_WARFRAME_SETS or
// PRIME_WEAPON_SETS), cross-referenced against the live warframe.market
// bulk item list purely for display data (name/icon/slug/price lookups) -
// the grouping itself never comes from warframe.market (see the
// module-level comment for why). A set is only emitted if BOTH its own
// listing AND every one of its member parts currently resolve against the
// bulk list - skips gracefully otherwise rather than emitting a partial/
// broken set.
//
// A weapon set's parts[] can list the same gameRef more than once (e.g. an
// Akimbo Prime needing 2x Barrel, or 2 whole copies of another Prime's own
// part set nested inside - see generate-prime-weapon-sets.js) - the grant
// list (the set's own `parts` field) needs every duplicate, but the flat
// per-part catalog row this function emits for browsing/selling
// individual parts only needs to exist once, so it's deduped by gameRef
// here. Warframe sets never have duplicates, so this is a no-op for them.
function buildPrimeCategoryItems(
    all: WfmItemEntry[],
    setDefs: PrimeSetDef[],
    resolveSlot: (gameRef: string) => PrimeSlot | null
): MarketItem[] {
    const byGameRef = new Map<string, WfmItemEntry>();
    for (const item of all) {
        if (item.gameRef) byGameRef.set(item.gameRef, item);
    }

    const result: MarketItem[] = [];

    for (const setDef of setDefs) {
        const setWfm = byGameRef.get(setDef.setGameRef);
        if (!setWfm?.i18n.en) continue;

        const resolvedParts = setDef.parts.map(def => ({ def, wfm: byGameRef.get(def.gameRef) }));
        if (resolvedParts.some(p => !p.wfm?.i18n.en)) continue;

        const seenGameRefs = new Set<string>();
        for (const { def, wfm } of resolvedParts) {
            if (seenGameRefs.has(def.gameRef)) continue;
            seenGameRefs.add(def.gameRef);

            const en = wfm!.i18n.en!;
            result.push({
                slug: wfm!.slug,
                gameRef: def.gameRef,
                name: en.name,
                icon: iconUrl(def.gameRef),
                category: def.category,
                type: "prime_part",
                defaultSubtype: "regular",
                maxRank: null,
                refinements: null,
                parts: null,
                slot: resolveSlot(def.gameRef),
                rarity: null,
                relicEra: null
            });
        }

        const setEn = setWfm.i18n.en;
        result.push({
            slug: setWfm.slug,
            gameRef: setDef.setGameRef,
            name: setEn.name,
            icon: iconUrl(setDef.setGameRef),
            category: "MiscItems", // unused for granting - the parts[] array below drives the grant loop, never this field
            type: "prime_set",
            defaultSubtype: "regular",
            maxRank: null,
            refinements: null,
            parts: resolvedParts.map(p => p.def),
            slot: null,
            rarity: null,
            relicEra: null
        });
    }

    return result;
}

async function refresh(): Promise<MarketItem[]> {
    const all = await fetchAllItems();
    const classified = all.map(classify).filter((m): m is MarketItem => m !== null);
    const primeItems = [
        ...buildPrimeCategoryItems(all, PRIME_WARFRAME_SETS, primeSlotFromGameRef),
        ...buildPrimeCategoryItems(all, PRIME_WEAPON_SETS, weaponPrimeSlotFromGameRef)
    ];
    cache = [...classified, ...primeItems];
    lastRefreshedAt = Date.now();
    saveToDisk();
    return cache;
}

// Zero network calls - serves whatever's already loaded (disk cache, seed,
// or the result of the last triggerManualCatalogRefresh()). Never rejects:
// there's simply nothing to serve yet on a genuinely fresh install with no
// seed and no completed refresh, which callers (routes.ts) treat as an
// empty catalog, not an error.
//
// `icon` is recomputed fresh here rather than trusting whatever's stored
// in `cache`/items-cache.json - it's cheap (a lookup + fs.existsSync per
// item) and means icon availability always reflects the CURRENT icon
// cache on disk, regardless of when the catalog was last refreshed vs.
// when icons were last extracted. Without this, an item classified before
// its icon folder was extracted (or vice versa - icons extracted in a
// past run, catalog re-seeded fresh since) would show a stale/incorrect
// icon forever until the next full catalog refresh happened to line up
// with a completed icon extraction. routes.ts's POST /api/update-data
// runs the catalog refresh and icon extraction as separate steps, so this
// ordering issue is real, not hypothetical.
export async function getItems(): Promise<MarketItem[]> {
    return cache.map(item => ({ ...item, icon: iconUrl(item.gameRef) }));
}

export interface CatalogStatus {
    state: "empty" | "seeded" | "live";
    itemCount: number;
    lastRefreshedAt: number | null;
    refreshInProgress: boolean;
}

export function getCatalogStatus(): CatalogStatus {
    const state = cache.length === 0 ? "empty" : lastRefreshedAt === null ? "seeded" : "live";
    return { state, itemCount: cache.length, lastRefreshedAt, refreshInProgress: refreshing !== null };
}

// User-triggered "Update Data" (routes.ts) - the ONLY way the catalog ever
// re-fetches from warframe.market now. Returns immediately if a refresh is
// already in progress; otherwise kicks one off and returns the promise so
// the caller can await it as part of the combined update-data flow (unlike
// priceCache's fire-and-forget sweep, this one's fast enough - a single
// request - to just await directly).
export function triggerManualCatalogRefresh(): Promise<MarketItem[]> {
    if (!refreshing) {
        refreshing = refresh().finally(() => {
            refreshing = null;
        });
    }
    return refreshing;
}

export async function findItemByGameRef(gameRef: string): Promise<MarketItem | undefined> {
    const items = await getItems();
    return items.find(m => m.gameRef === gameRef);
}

export async function findItemBySlug(slug: string): Promise<MarketItem | undefined> {
    const items = await getItems();
    return items.find(m => m.slug === slug);
}

// The real grantable/sellable ItemType path for an item at a given
// refinement - same resolution routes.ts already does when creating a
// sell order, factored out so the owned-count lookup (GET /api/owned)
// stays in sync with it rather than re-deriving the suffix logic
// separately. Only relics vary by refinement; everything else's gameRef
// IS the sellable path already (Sell is always rank-0 for mods/arcanes,
// and Prime parts/sets have no variants at all).
export function resolveSellGameRef(item: MarketItem, refinement?: string): string {
    if (item.type !== "relic") return item.gameRef;
    const chosen = typeof refinement === "string" && item.refinements?.includes(refinement) ? refinement : item.defaultSubtype;
    const suffix = RELIC_REFINEMENT_SUFFIXES[chosen];
    return suffix ? item.gameRef + suffix : item.gameRef;
}
