// Local, fully-offline icon extraction via Warframe-Exporter-CLI - see
// docs/public-export-reference.md §7 for the full CLI reference/gotchas
// (don't re-derive them here). Ported from OpenTools' already-verified
// server/src/localIcons.ts (confirmed working end-to-end 2026-09-21),
// adapted for this project's flat gameRef -> icon-path lookup instead of
// OpenTools' per-category WFCD data.
//
// This REPLACES warframe.market's own icon hotlink entirely (iconUrl() in
// itemsCache.ts used to return `https://warframe.market/static/assets/
// ${icon}` - now broken, per user report 2026-09-25, and a live network
// dependency either way). There is no network fallback for icons anymore:
// an item with no local icon extracted yet just shows the client-side
// placeholder (public/assets/no-icon.svg) until "Update Data" runs.
//
// Unlike OpenTools' fixed per-category folder map, the set of folders to
// extract here is derived AT RUNTIME from icon-paths.json (generated by
// tools/generate-icon-paths.js) - the distinct immediate parent directory
// of every icon path this app's catalog can actually reference. This
// matters because two of the "obvious" umbrella folders turned out to be
// far bigger than what this app needs and made extraction impractically
// slow (confirmed by trial, 2026-09-25): bulk-extracting the whole
// StoreIcons/Weapons tree (every Grineer/Corpus/Infested NPC weapon and
// every non-Prime Tenno weapon, not just this app's 87 Prime weapon sets)
// took over 10 minutes and was killed before finishing; the whole
// Interface/Cards/Images tree (every mod/augment/card image in the game,
// far beyond this app's ~1600 real mod/arcane entries) did the same.
// Extracting only the ~80 folders actually referenced by icon-paths.json
// is both correct (never misses a needed icon) and fast (each folder is
// small - the exact same folders relics/arcanes/warframes/weapons already
// proved fast to extract individually).

import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// gameRef -> internal Public Export icon path - see
// tools/generate-icon-paths.js's header comment for exactly which export
// files/categories feed this.
const ICON_PATHS: Record<string, string> = JSON.parse(fs.readFileSync(path.join(__dirname, "../icon-paths.json"), "utf8"));

export function getIconPathForGameRef(gameRef: string): string | null {
    return ICON_PATHS[gameRef] ?? null;
}

// A small number of icons (~30, all in ExportUpgrades.json/mods) sit
// directly in this shared root instead of a named subfolder of their own.
// Warframe-Exporter's --internal-path always recurses, and this exact
// root also contains large unrelated subtrees this app never needs (e.g.
// "Railjack" - confirmed via --ls, 2026-09-25) - extracting it pulls in
// everything underneath, reproducing the same 10+-minute problem the
// per-folder split above exists to avoid. Every OTHER folder in
// icon-paths.json was checked the same way and either has no
// subdirectories of its own or only ones already covered by this app's
// own needed-folder set (e.g. Cards/Images/Melee's "Galvanized"/
// "Tennokai" children are both separately in ICON_PATHS already) - this
// is the one genuine exception, not a guess. The ~30 icons here just show
// the placeholder instead of extracting this root.
const UNSAFE_BROAD_ROOTS = new Set(["/Lotus/Interface/Cards/Images"]);

// Distinct immediate parent directory of every icon path this app can
// reference - each one gets its own `--internal-path` extraction call.
const NEEDED_FOLDERS: string[] = [...new Set(Object.values(ICON_PATHS).map(p => p.split("/").slice(0, -1).join("/")))]
    .filter(folder => !UNSAFE_BROAD_ROOTS.has(folder))
    .sort();

// Mirrors OpenTools' EXPORTER_PATH default - other_software/ lives at the
// OPENWF _ Modding project root, shared across subprojects. Cross-platform
// since this app ships a Linux AppImage build too (v1.1.0 shipped an
// AppImage of the launcher itself for Steam Deck - offline play there is
// exactly what this whole icon feature needs to actually work, not just
// on Windows). Puxtril/Warframe-Exporter added a Linux release in v2.12
// (Dec 2025); the bundled `Warframe-Exporter-CLI.AppImage` here is v2.15.
const EXPORTER_FILENAME = process.platform === "win32" ? "Warframe-Exporter-CLI.exe" : "Warframe-Exporter-CLI.AppImage";
const EXPORTER_PATH =
    process.env.MARKET_EMULATOR_EXPORTER_PATH ??
    path.join(__dirname, "../../../other_software/warframe_exporter", EXPORTER_FILENAME);

// No sensible default - the client version (and therefore this path)
// changes over time, and guessing wrong would silently point at a
// stale/nonexistent install. Local extraction is simply OFF (every item
// shows the placeholder icon) until this is set.
const CACHE_WINDOWS_DIR = process.env.MARKET_EMULATOR_CACHE_DIR ?? null;

const CACHE_ROOT = path.join(__dirname, "../icon-cache");

export function isLocalExtractionAvailable(): boolean {
    if (CACHE_WINDOWS_DIR === null || !fs.existsSync(EXPORTER_PATH)) return false;
    // git doesn't reliably preserve the executable bit through a
    // clone/checkout on every platform/config - defensively (re-)set it
    // rather than have the AppImage silently fail to launch with a
    // confusing "Permission denied" the first time someone runs this on
    // Linux. A no-op if it's already executable.
    if (process.platform !== "win32") {
        try {
            fs.chmodSync(EXPORTER_PATH, 0o755);
        } catch {
            // Not fatal - the spawn below will surface a real error if
            // this genuinely isn't runnable.
        }
    }
    return true;
}

const extractedFolders = new Set<string>();
const inFlight = new Map<string, Promise<void>>();

// A folder path makes an unsafe filename as-is - flatten it to a single
// marker file name.
function markerPath(folder: string): string {
    return path.join(CACHE_ROOT, `.extracted-${folder.replace(/[^a-z0-9]+/gi, "_")}`);
}

function folderAlreadyExtracted(folder: string): boolean {
    if (extractedFolders.has(folder)) return true;
    if (fs.existsSync(markerPath(folder))) {
        extractedFolders.add(folder);
        return true;
    }
    return false;
}

async function extractFolder(folder: string): Promise<void> {
    if (!CACHE_WINDOWS_DIR) return;

    fs.mkdirSync(CACHE_ROOT, { recursive: true });

    await new Promise<void>((resolve, reject) => {
        const args = [
            "--cache-dir",
            CACHE_WINDOWS_DIR,
            "--package",
            "Texture",
            "--extract-textures",
            "--internal-path",
            folder,
            "--texture-format",
            "PNG",
            "--output-path",
            CACHE_ROOT
        ];
        // AppImages mount themselves via FUSE at launch - not guaranteed
        // present on every Linux setup (some minimal/containerized
        // environments, unclear for SteamOS specifically - UNTESTED on
        // real Steam Deck hardware from here). --appimage-extract-and-run
        // is the AppImage format's own documented fallback: extracts to a
        // temp dir and runs from there instead of mounting, at the cost
        // of a slower startup per call - acceptable for an occasional
        // manual bulk operation like this one. No-op/ignored on Windows.
        const spawnEnv = process.platform === "win32" ? undefined : { ...process.env, APPIMAGE_EXTRACT_AND_RUN: "1" };
        const child = spawn(EXPORTER_PATH, args, { env: spawnEnv });
        let stderr = "";
        child.stderr?.on("data", d => {
            stderr += d.toString();
        });
        child.on("error", reject);
        child.on("exit", code => {
            if (code === 0) resolve();
            else reject(new Error(`Warframe-Exporter-CLI exited ${code}: ${stderr.slice(0, 500)}`));
        });
    });

    fs.writeFileSync(markerPath(folder), new Date().toISOString());
    extractedFolders.add(folder);
}

// Fire-and-forget, one folder. Never throws - a failure just logs a
// warning and leaves that folder's items on the placeholder icon.
function ensureFolderCached(folder: string): Promise<void> {
    if (!isLocalExtractionAvailable()) return Promise.resolve();
    if (folderAlreadyExtracted(folder)) return Promise.resolve();
    if (inFlight.has(folder)) return inFlight.get(folder)!;

    const promise = extractFolder(folder)
        .catch(err => {
            console.error(
                `Icon cache: extraction failed for "${folder}" - items in this folder will show the placeholder icon. ${err instanceof Error ? err.message : err}`
            );
        })
        .finally(() => {
            inFlight.delete(folder);
        });
    inFlight.set(folder, promise);
    return promise;
}

// The user-triggered "Update Data" bulk operation (routes.ts) - runs every
// needed folder sequentially (these are local disk reads, not a rate-
// limited API, but sequential keeps progress/log output readable and
// avoids ~80 CLI processes hitting disk at once). Resolves once every
// folder has either finished or failed - callers should treat this as
// best-effort, same as the rest of this module. Skips folders already
// extracted from a previous run, so a re-run after this app's catalog
// gains new items only extracts what's actually new.
export async function ensureAllIconsCached(): Promise<void> {
    if (!isLocalExtractionAvailable()) return;
    console.log(`Icon cache: checking ${NEEDED_FOLDERS.length} folders...`);
    let extracted = 0;
    for (const folder of NEEDED_FOLDERS) {
        const wasAlreadyDone = folderAlreadyExtracted(folder);
        await ensureFolderCached(folder);
        if (!wasAlreadyDone) extracted++;
    }
    console.log(`Icon cache: done (${extracted} folder(s) newly extracted, ${NEEDED_FOLDERS.length - extracted} already cached).`);
}

export interface IconCacheStatus {
    localExtractionAvailable: boolean;
    extracting: boolean;
    totalFolders: number;
    extractedFolders: number;
}

export function getIconCacheStatus(): IconCacheStatus {
    const extractedCount = NEEDED_FOLDERS.filter(folderAlreadyExtracted).length;
    return {
        localExtractionAvailable: isLocalExtractionAvailable(),
        extracting: inFlight.size > 0,
        totalFolders: NEEDED_FOLDERS.length,
        extractedFolders: extractedCount
    };
}

// iconPath is the raw Public Export "/Lotus/..." path - the extractor
// preserves this exact directory structure under CACHE_ROOT (confirmed
// live, same as OpenTools' precedent), so this is a direct file check,
// not a guess. Returns a path relative to CACHE_ROOT for the caller to
// prefix with wherever it serves /icon-cache from - never an absolute
// filesystem path or a hardcoded port (this module doesn't know what port
// the server is running on).
export function getLocalIconPath(iconPath: string): string | null {
    const rel = iconPath.replace(/^\//, "");
    const full = path.join(CACHE_ROOT, rel);
    if (!fs.existsSync(full)) return null;
    return rel;
}

export function getCacheRoot(): string {
    return CACHE_ROOT;
}
